@HostAddress = https://web.nicesky-8f45a90c.westus2.azurecontainerapps.io

POST {{HostAddress}}/message
Content-Type: application/json
traceparent: {{$randomInt}}

{
  "message": "Hello {{$randomInt}}"
}
